version: "3.9"

services:
  web:
    build: .
    image: djangify-infra:prod
    environment:
      DJANGO_SECRET_KEY: super-secret-key
      DJANGO_ALLOWED_HOSTS: djangify.traefik.me
      DJANGO_DB_NAME: djangify        # Será sobreescrito por quien lo despliegue
      DJANGO_DB_USER: djangify_user   # "
      DJANGO_DB_PASSWORD: securepass  # "
      DJANGO_DB_HOST: mysql-service   # Nombre del servicio o IP real que te den
      DJANGO_DB_PORT: 3306
      DEBUG: 0
    networks:
      - traefik-public
    volumes:
      - static-data:/app/staticfiles
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`djangify.traefik.me`)"
        - "traefik.http.routers.django.entrypoints=web"
        - "traefik.http.services.django.loadbalancer.server.port=8000"
        - "traefik.docker.network=traefik-public"

volumes:
  static-data:

networks:
  traefik-public:
    external: true

