version: "3.9"

services:
  web:
    build: .
    image: djangify-infra:prod
    environment:
      DJANGO_SECRET_KEY: super-secret-key
      DJANGO_ALLOWED_HOSTS: djangify-django.ieti.site
      DJANGO_DB_NAME: djangify        # Será sobreescrito por quien lo despliegue
      DJANGO_DB_USER: djangify_user   # "
      DJANGO_DB_PASSWORD: securepass  # "
      DJANGO_DB_HOST: mysql-service   # Nombre del servicio o IP real que te den
      DJANGO_DB_PORT: 3306
      DEBUG: 0
    networks:
      - net
    volumes:
      - static-data:/app/staticfiles
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      labels:
            - "traefik.enable=true"
            - "traefik.port=8000"
            - "traefik.docker.network=net"
            - "traefik.frontend.rule=Host:djangify.ieti.site"
            - "traefik.http.services.django.loadbalancer.server.port=8000"

volumes:
  static-data:

networks:
  net:
    external: true

