version: "3.9"

services:
  web:
    image: djangify-infra:prod      # Asegúrate de que está construida y disponible en todos los nodos
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == swarm21

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.djangify.rule=Host(`djangify-django.ieti.site`)"
        - "traefik.http.routers.djangify.entrypoints=web"
        - "traefik.http.services.djangify.loadbalancer.server.port=8000"
        - "traefik.docker.network=traefik_net"

    environment:
      - DJANGO_DB_HOST=192.168.152.104
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=djangodb
      - DJANGO_DB_USER=django
      - DJANGO_DB_PASSWORD=django

    networks:
      - net

networks:
  net:
    external: true
    name: traefik_net

