version: '3.7'

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--configFile=/etc/traefik/traefik_static.yml"
    ports:
      - "80:80"
      - "8080:8080"
    # - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_static.yml:/etc/traefik/traefik_static.yml
    networks:
      - net
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  net:
    external: true
    name: traefik_net
