log:
  level: DEBUG

api:
  dashboard: true
  insecure: false #true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  routers:
    traefik-dashboard:
      rule: "Host(`djangify-traefik.ieti.site`) && PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - web
      middlewares:
        - dashboard-auth

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$2y$05$PHLkgBYUv0LiK9i/kUsfh.X0qpa5Vgj03e3Mr6GfGepkN3Sr8N/8i"
