log:
  level: DEBUG

api:
  dashboard: true
  insecure: false #true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
